### ISSUE TITLE
Prevent the bot from spamming the channel 

### ISSUE THREAD

**Issue by boreq** [lovelaced/glitzz#22]
The responses should be rate limited. This can be easily done by modifying the sender. A config param can specify how often the messages can be sent.

**Comment by lovelaced** [comment]
A good rule of thumb would be to compare some IRC clients' (such as weechat) built-in rate limiting.

**Comment by boreq** [comment]
https://github.com/irssi/irssi/blob/master/docs/manual.txt#L183


	Most (all?) IRC servers' flood protection works like this
	(from RFC 1459):

	--------
	* check to see if client's `message timer' is less than
	  current time (set to be equal if it is);

	* read any data present from the client;

	* while the timer is less than ten seconds ahead of the current
	  time, parse any present messages and penalize the client by
	  2 seconds for each message;

	which in essence means that the client may send 1 message every 2
	seconds without being adversely affected.
