### ISSUE TITLE
.help command

### ISSUE THREAD

**Issue by boreq** [lovelaced/glitzz#31]
This is a reminder that a potentially problematic `.help` command is needed.

The following features are needed:
- get a list of commands with `.help`
- display command help with `.help command_name`

This is problematic due to the way the modules are implemented. The modules have no knowledge about each other. Due to this the help command would have to be a solution existing at least partially outside of the modules.

Potential solution:
- get a list of commands with `.help`:
  - each module would implement an interface such as `GetCommandList() []string` returning available command names
  - when executing `.help` a piece of code living outside the modules could query all modules and assemble a list of commands to return
- display command help with `.help command_name`
  - this could be implemented directly in the modules
  - `core.Base` could automatically respond when encountering this command
  - the help strings would be added to `AddCommand` in the module constructors

**Comment by lovelaced** [comment]
too boring
