### ISSUE TITLE
Add sed module

### ISSUE THREAD

**Issue by boreq** [lovelaced/glitzz#41]
Replacing text in the last of your own messages that contains it:

     s/old/new

Replacing text in the last of someone else's messages that contains it:

    nick: s/old/new

**Comment by boreq** [comment]
Any implementation depending on external executables of any kind will cause the implementator to be whipped while jumping on one leg and writing an apology to Rob Pike.

**Comment by lovelaced** [comment]
Just needs additional options (g and i)
for example:
s/asd/test/gi
